name: burgertorch
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - pip
  - pip:
    - -r requirements.txt
    - -e .
prefix: /home/tony/.conda/envs/burgertorch
